### ISSUE TITLE
thread 'tokio-runtime-worker-0' panicked at 'User env var should exist: NotPresent'

### ISSUE THREAD

**Issue by ress997** [tootsuite/flodgatt#19]
I used a docker to make it work. https://github.com/ress997/docker-mastodon/compare/9468a1166909dd52c596da4c13134780e2ee9c34...a820a97c87ce4e2fd5c94d3bfed32b0a510f5ddb

And when I ran it with docker, an error occurred.

```
streaming_1  | thread 'tokio-runtime-worker-0' panicked at 'User env var should exist: NotPresent', src/libcore/result.rs:997:5
streaming_1  | stack backtrace:
streaming_1  |    0:     0x5584f37dd343 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h50ebfb8734a81144
streaming_1  |                                at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
streaming_1  |    1:     0x5584f37d7f7b - std::sys_common::backtrace::_print::hc7fdae4fb6b58d2d
streaming_1  |                                at src/libstd/sys_common/backtrace.rs:71
streaming_1  |    2:     0x5584f37db326 - std::panicking::default_hook::{{closure}}::hc55d0892611a29ff
streaming_1  |                                at src/libstd/sys_common/backtrace.rs:59
streaming_1  |                                at src/libstd/panicking.rs:197
streaming_1  |    3:     0x5584f37db0b9 - std::panicking::default_hook::h3c8a3df5d3469668
streaming_1  |                                at src/libstd/panicking.rs:211
streaming_1  |    4:     0x5584f37dba2f - std::panicking::rust_panic_with_hook::h24c9a1c35b1f49cc
streaming_1  |                                at src/libstd/panicking.rs:474
streaming_1  |    5:     0x5584f37db5b1 - std::panicking::continue_panic_fmt::h8ed9632bdd4b9299
streaming_1  |                                at src/libstd/panicking.rs:381
streaming_1  |    6:     0x5584f37db495 - rust_begin_unwind
streaming_1  |                                at src/libstd/panicking.rs:308
streaming_1  |    7:     0x5584f37f2cec - core::panicking::panic_fmt::h0d6d5c8b201e3246
streaming_1  |                                at src/libcore/panicking.rs:85
streaming_1  |    8:     0x5584f35c7b5d - core::result::unwrap_failed::h55b7b458f726c8bd
streaming_1  |    9:     0x5584f3615009 - ragequit::user::connect_to_postgres::ha5ebcb34139615e2
streaming_1  |   10:     0x5584f36150b2 - ragequit::user::User::from_access_token::h4ce6045af4488f98
streaming_1  |   11:     0x5584f35bb2a6 - <warp::filter::and_then::AndThenFuture<T,F> as futures::future::Future>::poll::he43a1486732218ba
streaming_1  |   12:     0x5584f35954fe - <warp::filter::and::AndFuture<T,U> as futures::future::Future>::poll::h231f8b8e18406e19
streaming_1  |   13:     0x5584f35b6c5d - <warp::filter::and_then::AndThenFuture<T,F> as futures::future::Future>::poll::h3a6f9d5714731d1e
streaming_1  |   14:     0x5584f35e247e - <warp::filter::or::EitherFuture<T,U> as futures::future::Future>::poll::hee0a8c4fd37564a1
streaming_1  |   15:     0x5584f35efb83 - hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch::haaed179ae9287640
streaming_1  |   16:     0x5584f362056b - <hyper::server::conn::spawn_all::NewSvcTask<I,N,S,E,W> as futures::future::Future>::poll::h6e0218e0394ebe3c
streaming_1  |   17:     0x5584f377a691 - futures::task_impl::std::set::h7038860475474ebb
streaming_1  |   18:     0x5584f377b485 - futures::task_impl::Spawn<T>::poll_future_notify::h1cb35ca6095edca0
streaming_1  |   19:     0x5584f377e950 - std::panicking::try::do_call::hd59aef5d7f79549e
streaming_1  |   20:     0x5584f37e0399 - __rust_maybe_catch_panic
streaming_1  |                                at src/libpanic_unwind/lib.rs:87
streaming_1  |   21:     0x5584f377ee3b - tokio_threadpool::task::Task::run::h2a745e7464345f86
streaming_1  |   22:     0x5584f3776e04 - tokio_threadpool::worker::Worker::run_task::h9f9065ed797646b2
streaming_1  |   23:     0x5584f37762fd - tokio_threadpool::worker::Worker::run::h0693e100e193ab57
streaming_1  |   24:     0x5584f375bd96 - tokio_trace_core::dispatcher::with_default::hcd2b6c0cd33ff8f9
streaming_1  |   25:     0x5584f375dab5 - std::thread::local::LocalKey<T>::with::h451c3e10ab344fb2
streaming_1  |   26:     0x5584f375dc7d - std::thread::local::LocalKey<T>::with::h57b0057e0f58ac86
streaming_1  |   27:     0x5584f375de03 - std::thread::local::LocalKey<T>::with::h6a0135e6d03037eb
streaming_1  |   28:     0x5584f37612e6 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h04801c2fe2a10930
streaming_1  |   29:     0x5584f377f852 - std::thread::local::LocalKey<T>::with::h6fc04725f0abf720
streaming_1  |   30:     0x5584f377f98d - std::thread::local::LocalKey<T>::with::hdcef3815128b4011
streaming_1  |   31:     0x5584f377e660 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc00dda4e78b7e6fd
streaming_1  |   32:     0x5584f377e99b - std::panicking::try::do_call::hdbe2e5364f5782c8
streaming_1  |   33:     0x5584f37e0399 - __rust_maybe_catch_panic
streaming_1  |                                at src/libpanic_unwind/lib.rs:87
streaming_1  |   34:     0x5584f377867f - core::ops::function::FnOnce::call_once{{vtable.shim}}::he3353550c5c4fdd9
streaming_1  |   35:     0x5584f37cdcde - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h4cac16ae2114a837
streaming_1  |                                at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/liballoc/boxed.rs:702
streaming_1  |   36:     0x5584f37df7df - std::sys::unix::thread::Thread::new::thread_start::h2adc1b80820f790e
streaming_1  |                                at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/liballoc/boxed.rs:702
streaming_1  |                                at src/libstd/sys_common/thread.rs:14
streaming_1  |                                at src/libstd/sys/unix/thread.rs:80
streaming_1  |   37:     0x7f06e65756da - start_thread
streaming_1  |   38:     0x7f06e608688e - __clone
streaming_1  |   39:                0x0 - <unknown>
```

I can't tell if this is working properly.

**Comment by codesections** [comment]
I believe this issue is caused by the Docker environment not setting the `USER` environmental variable (which would be set automatically in a non-containerized setting).  To resolve this, you can set the `USER` value in the `.env` file (that is add the line `USER=<THE_USER_FOR_THE_POSTGRESS_DB>` to the `.env` file).

**Comment by ress997** [comment]
Set environment variable successfully.

However, the error still occurs.
```
streaming_1  | thread 'tokio-runtime-worker-0' panicked at 'Can connect to local Postgres: Error(Io(Os { code: 101, kind: Other, message: "Network is unreachable" }))', src/libcore/result.rs:997:5
streaming_1  | stack backtrace:
streaming_1  |    0:     0x55836f121343 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h50ebfb8734a81144
streaming_1  |                                at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
streaming_1  |    1:     0x55836f11bf7b - std::sys_common::backtrace::_print::hc7fdae4fb6b58d2d
streaming_1  |                                at src/libstd/sys_common/backtrace.rs:71
streaming_1  |    2:     0x55836f11f326 - std::panicking::default_hook::{{closure}}::hc55d0892611a29ff
streaming_1  |                                at src/libstd/sys_common/backtrace.rs:59
streaming_1  |                                at src/libstd/panicking.rs:197
streaming_1  |    3:     0x55836f11f0b9 - std::panicking::default_hook::h3c8a3df5d3469668
streaming_1  |                                at src/libstd/panicking.rs:211
streaming_1  |    4:     0x55836f11fa2f - std::panicking::rust_panic_with_hook::h24c9a1c35b1f49cc
streaming_1  |                                at src/libstd/panicking.rs:474
streaming_1  |    5:     0x55836f11f5b1 - std::panicking::continue_panic_fmt::h8ed9632bdd4b9299
streaming_1  |                                at src/libstd/panicking.rs:381
streaming_1  |    6:     0x55836f11f495 - rust_begin_unwind
streaming_1  |                                at src/libstd/panicking.rs:308
streaming_1  |    7:     0x55836f136cec - core::panicking::panic_fmt::h0d6d5c8b201e3246
streaming_1  |                                at src/libcore/panicking.rs:85
streaming_1  |    8:     0x55836ef0b9a2 - core::result::unwrap_failed::h420dc0feaa2a9601
streaming_1  |    9:     0x55836ef59024 - ragequit::user::connect_to_postgres::ha5ebcb34139615e2
streaming_1  |   10:     0x55836ef590b2 - ragequit::user::User::from_access_token::h4ce6045af4488f98
streaming_1  |   11:     0x55836eeff2a6 - <warp::filter::and_then::AndThenFuture<T,F> as futures::future::Future>::poll::he43a1486732218ba
streaming_1  |   12:     0x55836eed94fe - <warp::filter::and::AndFuture<T,U> as futures::future::Future>::poll::h231f8b8e18406e19
streaming_1  |   13:     0x55836eefac5d - <warp::filter::and_then::AndThenFuture<T,F> as futures::future::Future>::poll::h3a6f9d5714731d1e
streaming_1  |   14:     0x55836ef2647e - <warp::filter::or::EitherFuture<T,U> as futures::future::Future>::poll::hee0a8c4fd37564a1
streaming_1  |   15:     0x55836ef33b83 - hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch::haaed179ae9287640
streaming_1  |   16:     0x55836ef6456b - <hyper::server::conn::spawn_all::NewSvcTask<I,N,S,E,W> as futures::future::Future>::poll::h6e0218e0394ebe3c
streaming_1  |   17:     0x55836f0be691 - futures::task_impl::std::set::h7038860475474ebb
streaming_1  |   18:     0x55836f0bf485 - futures::task_impl::Spawn<T>::poll_future_notify::h1cb35ca6095edca0
streaming_1  |   19:     0x55836f0c2950 - std::panicking::try::do_call::hd59aef5d7f79549e
streaming_1  |   20:     0x55836f124399 - __rust_maybe_catch_panic
streaming_1  |                                at src/libpanic_unwind/lib.rs:87
streaming_1  |   21:     0x55836f0c2e3b - tokio_threadpool::task::Task::run::h2a745e7464345f86
streaming_1  |   22:     0x55836f0bae04 - tokio_threadpool::worker::Worker::run_task::h9f9065ed797646b2
streaming_1  |   23:     0x55836f0ba2fd - tokio_threadpool::worker::Worker::run::h0693e100e193ab57
streaming_1  |   24:     0x55836f09fd96 - tokio_trace_core::dispatcher::with_default::hcd2b6c0cd33ff8f9
streaming_1  |   25:     0x55836f0a1ab5 - std::thread::local::LocalKey<T>::with::h451c3e10ab344fb2
streaming_1  |   26:     0x55836f0a1c7d - std::thread::local::LocalKey<T>::with::h57b0057e0f58ac86
streaming_1  |   27:     0x55836f0a1e03 - std::thread::local::LocalKey<T>::with::h6a0135e6d03037eb
streaming_1  |   28:     0x55836f0a52e6 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h04801c2fe2a10930
streaming_1  |   29:     0x55836f0c3852 - std::thread::local::LocalKey<T>::with::h6fc04725f0abf720
streaming_1  |   30:     0x55836f0c398d - std::thread::local::LocalKey<T>::with::hdcef3815128b4011
streaming_1  |   31:     0x55836f0c2660 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc00dda4e78b7e6fd
streaming_1  |   32:     0x55836f0c299b - std::panicking::try::do_call::hdbe2e5364f5782c8
streaming_1  |   33:     0x55836f124399 - __rust_maybe_catch_panic
streaming_1  |                                at src/libpanic_unwind/lib.rs:87
streaming_1  |   34:     0x55836f0bc67f - core::ops::function::FnOnce::call_once{{vtable.shim}}::he3353550c5c4fdd9
streaming_1  |   35:     0x55836f111cde - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h4cac16ae2114a837
streaming_1  |                                at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/liballoc/boxed.rs:702
streaming_1  |   36:     0x55836f1237df - std::sys::unix::thread::Thread::new::thread_start::h2adc1b80820f790e
streaming_1  |                                at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/liballoc/boxed.rs:702
streaming_1  |                                at src/libstd/sys_common/thread.rs:14
streaming_1  |                                at src/libstd/sys/unix/thread.rs:80
streaming_1  |   37:     0x7fee9764e6da - start_thread
streaming_1  |   38:     0x7fee9715f88e - __clone
streaming_1  |   39:                0x0 - <unknown>
```

**Comment by Shleeble** [comment]
that's not the same error... you need to make sure that Postgres is available to docker as a container or bound to the docker bridge ip.

**Comment by ress997** [comment]
I set `POSTGRES_ADDR` but I get an error saying "User env var should...".

What is the format of `POSTGRES_ADDR`?

**Comment by Gargron** [comment]
If your Postgres is outside of Docker, I recommend trying to use ragequit outside of Docker as well. Trying to connect a Docker container to an outside service is a PITA.

**Comment by codesections** [comment]
Recent updates to config variables should have solved this issue.  Please feel free to open a new one if you have further difficulty running Flodgatt.

**Comment by ress997** [comment]
Thank you for correcting it.
I'll try it later.
